"""updated relationship in user and event

Revision ID: e9e9a0387ce7
Revises: 21a8a18acec6
Create Date: 2023-09-28 15:04:41.485206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e9a0387ce7'
down_revision = '21a8a18acec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
